kind: pipeline
name: amd64

steps:
  - name: Get qemu
    image: busybox
    commands:
      - make build/qemu-x86_64-static

  - name: build
    image: plugins/docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: pipeline
name: arm

steps:
  - name: Get qemu
    image: busybox
    commands:
      - make build/qemu-arm-static

  - name: build
    image: plugins/docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-arm32v6
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v6
