kind: pipeline
name: amd64

steps:
  - name: build
    image: docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-amd64

---
kind: pipeline
name: arm

steps:
  - name: build
    image: docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-arm32v6
      build_args:
        - ARCH=arm
        - REPO=arm32v6
