kind: pipeline
name: amd64

steps:
  - name: qemu
    image: plugins/download
    source: https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1-1/x86_64_qemu-x86_64-static.tar.gz

  - name: prep
    image: busybox
    commands:
      - tar -xvf x86_64_qemu-x86_64-static.tar.gz
      - rm x86_64_qemu-x86_64-static.tar.gz

  - name: build
    image: plugins/docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: pipeline
name: arm

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: iamthefij/multiarch-pipeline-test
      auto_tag: true
      auto_tag_suffix: linux-arm32v6
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v6
