kind: pipeline
name: amd64

steps:
  - name: build
    image: docker
    commands:
      - make build

---
kind: pipeline
name: arm

steps:
  - name: build
    image: docker
    commands:
      - make cross-build-arm
